### ISSUE TITLE
Unadvertised dependency on emo

### ISSUE THREAD

**Issue by scottlyden** [corinne-riddell/Guide-to-DID-estimators#21]
Subject says it all.   

.# install.packages("devtools")
devtools::install_github("hadley/emo")

Anyway, this looks like a great resource.  I'm looking forward to giving it a closer look.  Best of luck with the paper; I'm looking forward to reading that as well.  Best,  Scott

**Comment by corinne-riddell** [comment]
Addressed here: https://github.com/corinne-riddell/Guide-to-DID-estimators/pull/22. Thank you for catching this!
